name: test_build
on:
  push: 
    branches: 
      - main 
  workflow_dispatch:
    
permissions: 
  contents: read 
concurrency:
  group: backend 
  cancel-in-progress: false 
jobs:
  test: 
    runs-on: ubuntu-latest 
    timeout-minutes: 3 
    steps:
      - name: checkout repo 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup python 
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: install dependency 
        run: | 
          pip install --upgrade pip
          pip install -r requirements.txt 
      - name: format repo 
        run: |
          pip install black
          black . --line-length 120
      - name: run lint 
        run: flake8 . --max-line-length=120 --statistics 
      - name: run scan 
        run: bandit -r . -ll -s B101,B102,B103,B104,B105
      - name: scan dependency 
        run: safety check --full-report 
      - name: run test 
        run: |
          pytest app/* -v --disable-warnings  --cov=. --cov-report=term-missing

   #=============
  #build image 
 #=============     
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 5 
    needs: test
    steps:
      - name: checkout repo 
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0
      #we will use docker buildx for faster build,more build features
      - name: docker build 
        uses: docker/setup-buildx-action@v3
      #cached the recent built image for faster build of image...
      - name: cache docker build 
        uses: actions/cache@v5.0.3
        with:
          key: ${{runner.os}}-cache-path-${{github.sha}}
          path: /tmp/cache 
          restore-keys:  ${{runner.os}}-cache-path-
        # we will use this to create a well defined image tag and labels ... good for dynamic tagging
      - name: generate image metadata  
        id: img_tag 
        uses: docker/metadata-action@v5
        with: 
          images: ${{vars.ECR_REG}}/${{vars.ECR_REPO}} 
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest 
        # This build the image 
      - name: build time 
        uses: docker/build-push-action@v6 
        with: 
          context: . 
          load: true 
          push: false 
          tags: ${{steps.img_tag.outputs.tags}}
          labels: ${{steps.img_tag.outputs.labels}}
          cache-from: type=local,src=/tmp/cache
          cache-to: type=local,dest=/tmp/cache-new 
          platforms: linux/amd64 
        # cleaning up the old cache file and replace it with a new one.. this increase the build time and clean up the cache directory
      - name: cleaning up old cached file 
        run: | 
          rm -rf /tmp/cache 
          mv /tmp/cache-new /tmp/cache 
      - name: check built image 
        run: docker images 
      - name: save image  
        id: saved
        run: | 
          image=$( echo "${{steps.img_tag.outputs.tags}}" | grep "sha-" | head -n 1)
          echo "saving now"
          #using .tar will compress the image for faster upload and download(artifact size minimized)
          docker save "$image" -o  backend_image.tar  
      - name: save image tag 
        run: |
          echo "${{steps.img_tag.outputs.tags}}" > backend_image_tag.txt
      - name: login to aws 
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume:  ${{secrets.AWS_ROLE}} #use role oidc much more safer and configure role in organization secrets
          aws-region: ${{secrets.AWS_REGION}} #save region in secret
      - name: send artifact to s3 bucket
        run: aws s3 cp backend_image.tar s3://project-a-kubernetes-s3-bucket 
      - name: send artifact metadata to s3 bucket
        run: aws s3 cp backend_image_tag.txt s3://project-a-kubernetes-s3-bucket 